name: 'Publish application'
on:
  push:
    branches:
      - master

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    
    env:
     CI: true
     PUBLISH_FOLDER: Samples/BlazorWebAssembly/Blazor-Wasm-Captcha-Test/bin/Release/net8.0/publish/wwwroot

    name: Build and Deploy Job
    steps:
      - name: Set the name of the repo in env variable 
        run: 
            echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
        
      - uses: actions/checkout@v4
      
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      #- name: Restore dependencies
      #  run: dotnet restore

      #- name: Restore .NET workloads
      #  run: dotnet workload restore
      
      - name: Install WebAssembly workload
        run: dotnet workload install wasm-tools

      - name: Check installed workloads (debug)
        run: dotnet workload list

      - name: Dotnet Publish
        run: dotnet publish --configuration Release -f net8.0

      - name: Debug publish output
        run: |
          echo "Listing output:"
          ls -R Samples/BlazorWebAssembly/Blazor-Wasm-Captcha-Test/bin/Release/net8.0/publish/

      - name: Change base-tag in index.html to repo name
        run: sed -i 's/<base href="\/" \/>/<base href="\/${{ env.REPO_NAME }}\/" \/>/g' $GITHUB_WORKSPACE/$PUBLISH_FOLDER/index.html
  
      - name: copy index.html to 404.html
        run: cp $GITHUB_WORKSPACE/$PUBLISH_FOLDER/index.html $GITHUB_WORKSPACE/$PUBLISH_FOLDER/404.html
      
      - name: Add .nojekyll file
        run: touch $PUBLISH_FOLDER/.nojekyll
        
      - name: Deploy GitHub Pages action
        uses: peaceiris/actions-gh-pages@v4
        with:
            github_token: ${{ secrets.PUBLISH_TOKEN_CAPTCHA }}
            publish_dir: ${{ env.PUBLISH_FOLDER }}
            allow_empty_commit: false
            keep_files: false
            force_orphan: true
            publish_branch: gh-pages
